---
- hosts: 172.31.21.198
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want to create folder
    file:
      path: /home/ubuntu/myfolder
      state: directory
  - name: i want to copy file from master to node
    copy: 
      src: my2ndfile.txt
      dest: /home/ubuntu/my2ndfile

  - name: i want to install apache2
    apt:
      name: apache2
      state: present 

  - name: copy dynofile into node side
    template:
      src: myindex.j2
      dest: /var/www/html/index.html