---
- hosts: all
  become: yes
  tasks:
  - name: i want to install webserver ubuntu
    apt:
      name: apache2
      state: present

  - name: i want to strated webserver
    service:
    - name: apache2
      state: started    